### ISSUE TITLE
Missing export_presets.cfg

### ISSUE THREAD

**Issue by merspieler** [virtual-puppet-project/vpuppr#100]
I'm trying to package openseeface-gd for nixOS.
When building, godot complains about a missing `export_presets.cfg` file.
Other godot based project I've packaged always had that file in the repo but here I couldn't find one.
I've seen that you've added the `export_presets.cfg` to the gitignore, on purpose, I assume.
Since I'm not too familiar with godot, can I just copy that file from a different project or could you please provide me one to build for Linux.

**Comment by ItsRogueRen** [comment]
I believe you need a custom one for this project, there should be another repo from Youwin for it

**Comment by you-win** [comment]
An `exports_presets.cfg` should be created by manually exporting the project from the editor once. I blacklisted the config so people wouldn't try to export the application using a default Godot template.

I would use the export templates provided [here](https://github.com/you-win/godot/releases/tag/3.3.2-gltf) in order to create a release build.

**Comment by merspieler** [comment]
Okay, I'll take a look at it... I've just never used the editor... so far I've only used `godot-headless --export`...

**Comment by you-win** [comment]
I thought about this further, and I think for CICD purposes I will need to include the `exports_presets.cfg` file anyways. I'll try and get this pushed at some point.

**Comment by merspieler** [comment]
Would make packaging it way easier.

**Comment by you-win** [comment]
Added back in 8a2ea0837fa81708b744c3308699653c1a9f1efa

Closing
